---
title: Service
description: "Academic service by Dr Justin C Yang, including editorial roles, expert advisory positions, peer review, and institutional contributions at UCL."

output:
  html_document:
    keep_md: yes
---
Dr Yang contributes to academic governance, open science, and peer review across UCL and the broader research community.

## Institutional Service
Unless otherwise indicated, service roles are current and/or ongoing.

### Internal

- Personal Tutor, Division of Psychiatry, University College London
- Culture Change Action Group Lead, Division of Psychiatry, University College London
- LGBTQ+ Equity Action Group, Division of Psychiatry, University College London
- Committee Member, Child and Young People's Mental Health ECR Network, University College London
- Open Science Champion, Faculty of Brain Science, University College London

### External

- Associate Editor, [Addiction](https://onlinelibrary.wiley.com/page/journal/13600443/homepage/editorialboard.html) 
- Editorial Board, [Substance Use: Research and Treatment](https://journals.sagepub.com/editorial-board/SAT) 
- Steering Committee Member, [Addiction Healthcare Goals ](https://www.gov.uk/government/publications/life-sciences-healthcare-goals/addiction-healthcare-goals)
- Expert Member, [Confidentiality Advisory Group, Health Research Authority ](https://www.hra.nhs.uk/about-us/committees-and-services/confidentiality-advisory-group/)
- Data Access Committee Public Member, [Eastern England Secure Data Environment](https://easternsde.nhs.uk/)
- Public Member, [British Society for Immunology](https://www.immunology.org/) Patient and Public Involvement Network 
- Expert Assessor, [Administrative Data Research UK](https://www.adruk.org/)
- Assessor College, [Economic and Social Research Council](https://www.ukri.org/councils/esrc/)
- Reviewer College, [Society for the Study of Addiction](https://www.addiction-ssa.org/)
- Reviewer Development Scheme, [National Institute for Health and Care Research ](https://www.nihr.ac.uk/)
- Ambassador, [Protocols.io ](https://www.protocols.io/)

## Peer Review Service
Publications for which I have served as a peer referee include:

```{r results = 'asis', echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(tidyverse)
library(httr2)
library(rcrossref)

orcid_id <- "0000-0003-2881-4906"

resp <- request(paste0("https://pub.orcid.org/v3.0/", orcid_id, "/peer-reviews")) |>
  req_headers(Accept = "application/json") |>
  req_perform()

body <- resp_body_json(resp)

raw <- map_chr(body$group, \(g) {
  val <- g$`external-ids`$`external-id`[[1]]$`external-id-value`
  if (is.null(val)) NA_character_ else val
})

issns_clean <- raw[!is.na(raw) & str_starts(raw, "issn:")] |>
  str_remove("^issn:") |>
  unique()

get_title_from_issn <- function(issn) {
  tryCatch({
    result <- rcrossref::cr_journals(issn)$data$title
    if (is.null(result) || length(result) == 0) return(NA_character_)
    result[[1]]
  }, error = \(e) NA_character_)
}

journal_names <- map_chr(issns_clean, get_title_from_issn) |>
  (\(x) x[!is.na(x)])() |>
  unique() |>
  str_squish() |>
  str_replace("Men s", "Men's") |>
  (\(x) x[order(str_remove(x, regex("^(the|a|an)\\s+", ignore_case = TRUE)))])()

cat(paste0("- ", journal_names), sep = "\n")
```
