---
title: Publications

output:
  html_document:
    keep_md: yes
---

## Peer-Reviewed Publications
```{r include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(scholar)
library(tidyverse)

publications <- as_tibble(get_publications("o-MsbBYAAAAJ")) %>%
  arrange(desc(year)) %>%
  mutate(author_long =
           case_when(str_detect(author, pattern = "\\.\\.\\.$") ~ 1, TRUE ~ 0)) %>%
  mutate(author = case_when(
    author_long == 1 ~ get_complete_authors("o-MsbBYAAAAJ", pubid),
    TRUE ~ author
  )) %>%
  mutate(
    author = str_replace_all(author, "([A-Z]) ([A-Z]) ", "\\1\\2 "),
    author = str_replace_all(author, "JC Yang", "**JC Yang**"),
    author = str_replace_all(author, "J Yang", "**J Yang**"),
    title = str_replace_all(title, ":.+", ""),
    author = str_replace(author, ", (?=[^,]*$)", ", and ")
  ) %>%
  mutate(cid = case_when(
    str_detect(pubid,
               "IWHjjKOFINEC") ~ "15882838923600769415",
    TRUE ~ cid
  )) %>%
  mutate(cid = case_when(
    str_detect(pubid,
               "4DMP91E08xMC") ~ "6138374257100904004",
    TRUE ~ cid
  )) %>%
  split(desc(.$year)) %>%
  map(function(x) {
    x <- x %>%
      mutate(
        citation = paste0(
          author,
          ". ",
          "(",
          year,
          ").",
          " ",
          "[",
          title,
          "]",
          "(https://scholar.google.com/scholar?oi=bibs&cluster=",
          cid,
          "&btnI=1&hl=en)",
          ". ",
          "*",
          journal,
          "*",
          " ",
          number,
          "."
        )
      ) %>%
      select(citation)
    return(x)
  })

publications <-
  map2(substring(names(publications), 2) %>% paste0("<!--", ., "-->"),
       publications,
       c) %>% unlist %>% as_tibble() %>% mutate(value = gsub("Rv Kessel", "R van Kessel", value)) %>% pivot_wider(names_from = value) 
```
```{r results = 'asis', echo=FALSE, message=FALSE, warning=FALSE}
cat(paste0(publications), sep = "\r  \n")
```  

## Preprints
```{r include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(medrxivr)
library(tidyverse)
library(here)

# medrxivdata <- mx_api_content(from_date = "2021-01-01")
# saveRDS(medrxivdata, here("medrxivdata.rds"))

medrxivdata <- readRDS(here("medrxivdata.rds"))

reformat_authors <- function(author_str) {
  # Split the input string into individual authors
  authors <- str_split(author_str, ";\\s+")[[1]]
  
  # Process each author name and store them in a new vector
  formatted_authors <- sapply(authors, function(author) {
    names_parts <- str_split(author, ",\\s+")[[1]]
    last_name <- names_parts[1]
    initials <- str_extract_all(names_parts[2], "[A-Za-z]") %>% paste(collapse = "")
    initials <- gsub("(\\w)", "\\1.", initials, perl = TRUE)  # Add periods after each initial
    initials <- gsub("", "", initials)  # Remove any spaces between initials
    return(paste0(initials, " ", last_name))
  })
  
  # Combine the formatted author names back into a single string
  formatted_authors_str <- paste(formatted_authors, collapse = ", ")
  return(formatted_authors_str)
}

preprints <- mx_search(data = medrxivdata,
          query = c("10.1101/2021.11.28.21266870",
                    "10.1101/2022.12.15.22283515",
                    "10.1101/2023.03.29.23287850"), 
          fields = c("doi")
          ) |> 
  filter(grepl("NA",published) |
           is.na(published)) |> 
  select(authors, title, date, link_page) |> 
  mutate(authors = sapply(authors, reformat_authors)) |> 
    mutate(
    authors = str_replace_all(authors, 'c\\.\\(\\"',''),
authors = str_replace_all(authors, '\\.\\"\\, \\"', ''),
authors = str_replace_all(authors, '\\.\\"\\)', ''),
authors = str_replace_all(authors, '\\.', ''),
authors = str_replace_all(authors, 'JC Yang', '**JC Yang**'),
authors = str_replace(authors, ", (?=[^,]*$)", ", and ")) |> 
  mutate(date = str_sub(date,1,4)) |> 
  mutate(citation = paste0(
          authors,
          ". ",
          "(",
          date,
          ").",
          " ",
          "[",
          title,
          "]",
          "(",
          link_page,
          ")",
          "."
        )) |> 
  select(citation) |> 
  unlist() |> 
  as_tibble()  |>
  pivot_wider(names_from = value) 

```
```{r results = 'asis', echo=FALSE, message=FALSE, warning=FALSE}
cat(paste0(preprints), sep = "\r  \n")
``` 
