baseurl: "https://www.justinyang.me"
locale: "en-GB"
title: "MINDSET"
theme: "hugo-xmin"

security:
  allowContent:
    - "text/html"
    - "text/markdown"

ignoreFiles:
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_cache$"
  - "\\.knit\\.md$"
  - "\\.utf8\\.md$"

footnotereturnlinkcontents: "↩"

permalinks:
  presentations: "/presentations/:year/:month/:day/:title/"

menu:
  main:
    - name: Home
      url: "/"
      weight: 1

    - name: Research
      url: "research/"
      weight: 2

    - name: People
      url: "people/"
      weight: 3

    - name: Publications
      url: "publications/"
      weight: 4

    - name: Funding
      url: "funding/"
      weight: 5

    - name: Talks
      url: "talks/"
      weight: 6

    - name: Teaching
      url: "teaching/"
      weight: 7

    - name: Leadership
      url: "leadership/"
      weight: 8

    - name: Contact
      url: "contact/"
      weight: 9

params:
  description: "MINDSET is the research programme led by Dr Justin C Yang at UCL, using psychiatric epidemiology, linked data, causal inference, and data science to understand mental health, inequalities, and care."
  footer: "MINDSET · Dr Justin C Yang · University College London <br> &copy; [Justin C Yang](https://www.justinyang.me) 2019-{Year}"
  githubSource: "https://github.com/yangjustinc/yangjustinc-blogdown/blob/main/content/"
  ogImage: "twitter_card.jpg"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
