---
title: Teaching & Supervision
---
# University College London
I'm a Teaching Assistant for the [Practical Statistics for Mental Health Research](https://www.ucl.ac.uk/module-catalogue/modules/practical-statistics-for-mental-health-research/PSBS0008) module on the [MSc in Mental Health Sciences Research](https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/mental-health-sciences-research-msc) course. I also mark for the [Current Research in Depression and Anxiety](https://www.ucl.ac.uk/psychiatry/mental-health-sciences-modules/current-research-depression-and-anxiety) and [Current Research in Psychosis and Bipolar Disorder](https://www.ucl.ac.uk/psychiatry/mental-health-sciences-modules/current-research-psychosis-and-bipolar-disorder) modules. I'm always happy to co-supervise MSc students completing their dissertations using the [Research Database at Camden & Islington NHS Foundation Trust](https://www.candi.nhs.uk/health-professionals/research/ci-research-database).

# Queen Mary University of London
I'm a dissertation supervisor on the [MSc in Global Public Health and Policy](https://www.qmul.ac.uk/postgraduate/taught/coursefinder/courses/global-public-health-and-policy-msc) course where I mainly supervise projects pertaining to secondary data analysis, substance-related use disorders, and comparative health policy. I normally supervise 1-2 students per term.

# University of Cambridge
I conducted supervisions on quantitative research methods and secondary data analysis to students on the [MPhil in Population Health Sciences](https://www.phs.masters.cam.ac.uk) course.