---
title: Coauthorship Network

output:
  html_document:
    keep_md: yes
---
This network diagram shows my second-order coauthorship network, that is, coauthors with whom I share at least one publication and their coauthors on their own papers (provided they are registered on ORCID). Colours represent distinct dense subgraphs observed when optimising a modularity score.

```{r include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(rorcid)

library(tidyr)
library(janitor)
library(dplyr)
library(stringr)

library(networkDynamic)
library(ndtv)
library(intergraph)
library(igraph)
library(statnet)
library(visNetwork)
library(plotly)
library(GGally)

# target_orcid <- "0000-0003-2881-4906"
# 
# get_doi <- function(x) {
#   list.x <- orcid_works(x)[[1]]$works$`external-ids.external-id`
#   list.x <- list.x[lapply(list.x,length)>0]
#   do.call(rbind.data.frame, lapply(list.x, function(x) {
#     if (length(x) == 0 | (!'doi' %in% x[, 1]) | ('isbn' %in% x[, 1])) {
#       data.frame(value = NA)
#     } else{
#       data.frame(value = x[which(x[, 1] %in% 'doi'), 2])
#     }
#   }))
# }
# 
# get_papers <- function(x) {
#   papers <- data.frame(doi   = get_doi(x))
#   
#   paper.doi <- lapply(1:nrow(papers), function(x) {
#     if (!is.na(papers[x, 1]))return(orcid_doi(dois = check_dois(papers[x, 1])$good, fuzzy = FALSE))
#     return(NA)
#   })
#   
#   your.papers <- lapply(1:length(paper.doi), function(x) {
#     if (length(paper.doi[[x]]) == 0 || is.na(paper.doi[[x]])) {
#       data.frame(doi = NA, orcid = NA)
#     } else {
#       data.frame(
#         doi = papers[x, 1],
#         orcid = paper.doi[[x]][[1]]$`orcid-identifier.path`,
#         stringsAsFactors = FALSE
#       )
#     }
#   })
#   
#   do.call(rbind.data.frame, your.papers)
#   
# }
# 
# paper.set <- get_papers(target_orcid) %>% drop_na()
# 
# unique.orcids <- unique(paper.set$orcid)
# 
# all.coauthors <- list()
# 
# for(i in 1:length(unique.orcids)){
#   cat("Processing", i, "of", length(unique.orcids), ", orcid = ", unique.orcids[i], "\n")
#   all.coauthors[[i]] <- get_papers(unique.orcids[i])
# }
# 
# all.df <- do.call(rbind.data.frame, all.coauthors)
# 
# all.df.names <- all.df %>% select(orcid) %>% distinct(orcid) %>%
#   drop_na() %>%
#   rowwise() %>% 
#   mutate(name = str_to_title(str_squish(paste0(orcid_id(orcid)[[1]]$name$`given-names`$value, " ",
#                       orcid_id(orcid)[[1]]$name$`family-name`$value)))) %>%
#   ungroup()
# 
# all.df <- all.df %>% left_join(all.df.names)
# all.df <- na.omit(all.df[!duplicated(all.df),])
# 
# 
# all.pairs <- matrix(ncol = length(unique(all.df$name)),
#                     nrow = length(unique(all.df$name)),
#                     dimnames = list(unique(all.df$name),unique(all.df$name)), 0)
# unique.dois <- unique(as.character(all.df$doi))
# 
# all.pairs <- all.pairs[rowSums(all.pairs)>0, colSums(all.pairs)>0]
# 
# diag(all.pairs) <- 0
# 
# statnet <-
#   as.network(all.pairs,
#              directed = FALSE,
#              names.eval = "edge.lwd",
#              ignore.eval = FALSE)
# 
# igraph <- asIgraph(statnet)
# 
# modules <- cluster_fast_greedy(igraph)
# V(igraph)$color = modules$membership
# statnet %v% "membership" <- modules$membership
# 
# save(
#   all.coauthors,
#   all.df,
#   all.pairs,
#   modules,
#   unique.dois,
#   unique.orcids,
#   igraph,
#   statnet,
#   file = "output.rda")

```
```{r echo=FALSE, message=FALSE, warning=FALSE, out.width='100%'}
load("output.rda")

Noax <- list(
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE,
  autorange = TRUE
)
ggplotly(
  ggnet2(
    statnet,
    label =  TRUE,
    size = "degree",
    size.cut = 4,
    color = "membership",
    edge.color = 'lightgray',
    label.size = 3,
    palette = "Pastel1",
    mode = "fruchtermanreingold",
    layout.par = list(cell.jitter = 1)
  )
) %>%
  layout(
    hovermode = FALSE,
    showlegend = FALSE,
    xaxis = Noax,
    yaxis = Noax,
    dragmode = FALSE
  )
```  

Last generated from <a href = "https://orcid.org/0000-0003-2881-4906"><i class="ai ai-orcid"></i></a> on `r format(Sys.time(), '%d %B, %Y')`
