---
name: Justin C
surname: Yang
position: "Research Fellow in Psychiatric Epidemiology"
address: "Division of Psychiatry, University College London"
www: justinyang.me
email: "justin.yang@ucl.ac.uk"
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(stringr)
library(vitae)
library(rorcid)
library(scholar)
library(medrxivr)
library(here)
```
# Education
```{r}
educations <- do.call("rbind",
  rorcid::orcid_educations("0000-0003-2881-4906")$`0000-0003-2881-4906`$`affiliation-group`$summaries
)
educations %>%
  detailed_entries(
    with = `education-summary.organization.name`,
    when = glue::glue("{`education-summary.start-date.year.value`} - {`education-summary.end-date.year.value`}"),
    what = `education-summary.role-title`,
    where = glue::glue("{`education-summary.organization.address.city`}, {`education-summary.organization.address.country`}")
  )
```  
# Professional Appointments
```{r}
employments <- do.call("rbind",
  rorcid::orcid_employments("0000-0003-2881-4906")$`0000-0003-2881-4906`$`affiliation-group`$summaries
)
employments %>%
  detailed_entries(
    with = `employment-summary.organization.name`,
    when = glue::glue("{`employment-summary.start-date.year.value`} - Present"),
    what = `employment-summary.role-title`,
    where = glue::glue("{`employment-summary.organization.address.city`}, {`employment-summary.organization.address.country`}")
  )
```  
# Service and Professional Membership
```{r}
services <- do.call("rbind",
  rorcid::orcid_services("0000-0003-2881-4906")$`0000-0003-2881-4906`$`affiliation-group`$summaries
)
services %>%
  detailed_entries(
    with = `service-summary.organization.name`,
    when = glue::glue("{`service-summary.start-date.year.value`} - Present"),
    what = `service-summary.role-title`,
    where = glue::glue("{`service-summary.organization.address.city`}, {`service-summary.organization.address.country`}")
  )
```
# Publications
```{r include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(scholar)
library(tidyverse)

publications <- as_tibble(get_publications("o-MsbBYAAAAJ")) %>%
    arrange(desc(year)) %>%
  mutate(author_long =
           case_when(str_detect(author, pattern = "\\.\\.\\.$") ~ 1, TRUE ~ 0)) %>%
  mutate(author = case_when(
    author_long == 1 ~ get_complete_authors("o-MsbBYAAAAJ", pubid),
    TRUE ~ author
  )) %>%
  mutate(
    author = str_replace_all(author, "([A-Z]) ([A-Z]) ", "\\1\\2 "),
    author = str_replace_all(author, "JC Yang", "**JC Yang**"),
    author = str_replace_all(author, "J Yang", "**J Yang**"),
    author = str_replace_all(author, "Rv Kessel", "R van Kessel"),
    title = str_replace_all(title, ":.+", ""),
    author = str_replace(author, ", (?=[^,]*$)", ", and "),
    number = n():1) %>%
    arrange(desc(number)) %>%
      mutate(citation = paste0(
#          number,
#          ".\t",
          author,
          ". ",
          "(",
          year,
          ").",
          " ",
          title,
          ". ",
          "*",
          journal,
          "*",
          "."
        )) %>%
      select(citation)

publications <- publications %>% 
  unlist %>% 
  as_tibble() %>% 
  pivot_wider(names_from = value)
```
```{r results = 'asis', echo=FALSE, message=FALSE, warning=FALSE}
cat(paste0(publications), sep = "  \r  \n", fill = TRUE, labels = paste0(""))

```  

# Preprints
```{r include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
reformat_authors <- function(author_str) {
  # Split the input string into individual authors
  authors <- str_split(author_str, ";\\s+")[[1]]
  
  # Process each author name and store them in a new vector
  formatted_authors <- sapply(authors, function(author) {
    names_parts <- str_split(author, ",\\s+")[[1]]
    last_name <- names_parts[1]
    initials <- str_extract_all(names_parts[2], "[A-Za-z]") %>% paste(collapse = "")
    initials <- gsub("(\\w)", "\\1.", initials, perl = TRUE)  # Add periods after each initial
    initials <- gsub("", "", initials)  # Remove any spaces between initials
    return(paste0(initials, " ", last_name))
  })
  
  # Combine the formatted author names back into a single string
  formatted_authors_str <- paste(formatted_authors, collapse = ", ")
  return(formatted_authors_str)
}

preprints <- mx_search(data = mx_api_content(from_date = "2021-01-01"),
          query = c("10.1101/2021.11.28.21266870",
                    "10.1101/2022.12.15.22283515",
                    "10.1101/2023.03.29.23287850"), 
          fields = c("doi")
          ) |> 
  filter(grepl("NA",published) |
           is.na(published)) |> 
  select(authors, title, date, link_page) |> 
  arrange(desc(date)) |>
  mutate(authors = sapply(authors, reformat_authors)) |> 
    mutate(
    authors = str_replace_all(authors, 'c\\.\\(\\"',''),
authors = str_replace_all(authors, '\\.\\"\\, \\"', ''),
authors = str_replace_all(authors, '\\.\\"\\)', ''),
authors = str_replace_all(authors, '\\.', ''),
authors = str_replace_all(authors, 'JC Yang', '**JC Yang**'),
authors = str_replace(authors, ", (?=[^,]*$)", ", and "),
) |> 
  mutate(date = str_sub(date,1,4)) |> 
  mutate(number = n():1) |>
  arrange(desc(number)) |>
  mutate(citation = paste0(
#    number,
#          ".\t",
          authors,
          ". ",
          "(",
          date,
          ").",
          " ",
          title,
          ".",
          " ",
          "medRxiv."
        )) |> 
        arrange(desc(date)) %>%
  select(citation) |> 
  unlist() |> 
  as_tibble()  |>
  pivot_wider(names_from = value) 
```
```{r results = 'asis', echo=FALSE, message=FALSE, warning=FALSE}
cat(paste0(preprints), sep = "  \r  \n", fill = TRUE, labels = paste0(""))

```
<!-- # Funding -->
```{r results = 'asis',echo=FALSE, message=FALSE, warning=FALSE, error = FALSE}
# library(tidyverse)
# library(janitor)
# library(rorcid)
# 
# orcid <- "0000-0001-8130-5137"
# 
# # Must have all variables or function will report error
# 
# funding <-  do.call("rbind",
#   orcid_fundings(orcid)[[1]]$group$`funding-summary`) %>%
#   clean_names() %>%
#   select(put_code, title_title_value, start_date_year_value, end_date_year_value, organization_name) %>%
#   rename(
#     title = title_title_value,
#     year_start = start_date_year_value,
#     year_end = end_date_year_value,
#     funder_name = organization_name
#   ) %>% 
#   group_by(put_code) %>%
#   mutate(funding_amount = orcid_fundings(orcid, put_code = put_code)[[1]]$amount$value,
#          funding_currency = orcid_fundings(orcid, put_code = put_code)[[1]]$amount$`currency-code`,
#          description = orcid_fundings(orcid, put_code = put_code)[[1]]$`short-description`,
#          url = orcid_fundings(orcid, put_code = put_code)[[1]]$`external-ids`$`external-id`$`external-id-url.value`
#          ) %>%
#   ungroup()
# 
# funding %>%
#   detailed_entries(
#     with = funder_name,
#     when = paste0(year_start," - ",year_end),
#     what = title,
#     where = paste0(funding_currency," ",funding_amount),
#     why = str_squish(description)
#     )
```  
