#................................................
# Modified from mlampros/My.CVitae
#................................................

name: CV

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * SUN"
  push:
    branches: master

env:
  ORCID_TOKEN: "7348c78b-0dd7-412d-8d77-79f553df8712"

jobs:
  build:
    name: create the cv
    runs-on: ubuntu-latest
    container:
      image: mlampros/mycvitae:rstudiodev
    steps:
     - name: Set up Git repository
       uses: actions/checkout@v2
     - name: install texlive
       run: |
          sudo apt-get -y update
          sudo apt-get install -y texlive-base texlive-latex-base
          sudo apt-get install -y texlive-latex-recommended
          sudo apt-get install -y texlive-xetex
          sudo apt-get install -y texlive-fonts-extra
     - name: render the cv
       run: |
         Rscript -e "print(getwd())"
         Rscript -e "install.packages('medrxivr')"
         Rscript -e "rmarkdown::render(input = file.path(getwd(), 'static', 'cv', 'cv.Rmd'), params = list(work_dir = getwd()))"
     - name: commit files
       run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "upload cv to Github"
          git push
     - name: upload pdf file
       uses: actions/upload-artifact@v1
       with:
         name: cv
         path: static/cv/
