# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: '0  12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: publications

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
      
      - name: Install packages, render Rmarkdown Readme file and Commit Results
        run: |
          echo "Rendering the page..."
          Rscript -e 'install.packages(c("scholar", "tidyverse","medrxvir","here"))'
          Rscript -e 'rmarkdown::render(input = "content/publications/index.Rmd")'
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add *
            git commit -m "Auto update Report"
            git push origin
          fi
